// Generated by flowir.Codegen — do not edit.
import {
  defineFlow,
  acpNode,
  actionNode,
  computeNode,
  decisionNode,
  checkpointNode,
  forkNode,
  joinNode,
  endNode,
  edge,
} from "acpx";

export default defineFlow({
  id: "hello-review",
  name: "Hello + Review",
  start: "draft",
  nodes: [
    acpNode({ id: "draft", title: "Draft greeting", agentId: "writer-1", skill: "draft", prompt: "Write a friendly hello.", args: {} }),
    checkpointNode({ id: "review", title: "Human review", prompt: "Approve the draft?", approvers: [ "alice" ], timeoutSeconds: 3600, onTimeout: "escalate" }),
    actionNode({ id: "post", title: "Post greeting", fn: "post_message", args: { "channel": "general" } }),
    endNode({ id: "done", title: "Done" }),
  ],
  edges: [
    edge("draft", "review"),
    edge("review", "post"),
    edge("post", "done"),
  ],
});
