// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: execution/v1/execution.proto

package executionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutionService_StartRun_FullMethodName          = "/execution.v1.ExecutionService/StartRun"
	ExecutionService_GetRun_FullMethodName            = "/execution.v1.ExecutionService/GetRun"
	ExecutionService_ListRuns_FullMethodName          = "/execution.v1.ExecutionService/ListRuns"
	ExecutionService_ApproveCheckpoint_FullMethodName = "/execution.v1.ExecutionService/ApproveCheckpoint"
	ExecutionService_RejectCheckpoint_FullMethodName  = "/execution.v1.ExecutionService/RejectCheckpoint"
	ExecutionService_StreamRunEvents_FullMethodName   = "/execution.v1.ExecutionService/StreamRunEvents"
)

// ExecutionServiceClient is the client API for ExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecutionServiceClient interface {
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error)
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error)
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	ApproveCheckpoint(ctx context.Context, in *ApproveCheckpointRequest, opts ...grpc.CallOption) (*ApproveCheckpointResponse, error)
	RejectCheckpoint(ctx context.Context, in *RejectCheckpointRequest, opts ...grpc.CallOption) (*RejectCheckpointResponse, error)
	StreamRunEvents(ctx context.Context, in *StreamRunEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
}

type executionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutionServiceClient(cc grpc.ClientConnInterface) ExecutionServiceClient {
	return &executionServiceClient{cc}
}

func (c *executionServiceClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRunResponse)
	err := c.cc.Invoke(ctx, ExecutionService_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunResponse)
	err := c.cc.Invoke(ctx, ExecutionService_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) ApproveCheckpoint(ctx context.Context, in *ApproveCheckpointRequest, opts ...grpc.CallOption) (*ApproveCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveCheckpointResponse)
	err := c.cc.Invoke(ctx, ExecutionService_ApproveCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) RejectCheckpoint(ctx context.Context, in *RejectCheckpointRequest, opts ...grpc.CallOption) (*RejectCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectCheckpointResponse)
	err := c.cc.Invoke(ctx, ExecutionService_RejectCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executionServiceClient) StreamRunEvents(ctx context.Context, in *StreamRunEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecutionService_ServiceDesc.Streams[0], ExecutionService_StreamRunEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRunEventsRequest, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_StreamRunEventsClient = grpc.ServerStreamingClient[RunEvent]

// ExecutionServiceServer is the server API for ExecutionService service.
// All implementations should embed UnimplementedExecutionServiceServer
// for forward compatibility.
type ExecutionServiceServer interface {
	StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error)
	GetRun(context.Context, *GetRunRequest) (*GetRunResponse, error)
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	ApproveCheckpoint(context.Context, *ApproveCheckpointRequest) (*ApproveCheckpointResponse, error)
	RejectCheckpoint(context.Context, *RejectCheckpointRequest) (*RejectCheckpointResponse, error)
	StreamRunEvents(*StreamRunEventsRequest, grpc.ServerStreamingServer[RunEvent]) error
}

// UnimplementedExecutionServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutionServiceServer struct{}

func (UnimplementedExecutionServiceServer) StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedExecutionServiceServer) GetRun(context.Context, *GetRunRequest) (*GetRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedExecutionServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedExecutionServiceServer) ApproveCheckpoint(context.Context, *ApproveCheckpointRequest) (*ApproveCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveCheckpoint not implemented")
}
func (UnimplementedExecutionServiceServer) RejectCheckpoint(context.Context, *RejectCheckpointRequest) (*RejectCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectCheckpoint not implemented")
}
func (UnimplementedExecutionServiceServer) StreamRunEvents(*StreamRunEventsRequest, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamRunEvents not implemented")
}
func (UnimplementedExecutionServiceServer) testEmbeddedByValue() {}

// UnsafeExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutionServiceServer will
// result in compilation errors.
type UnsafeExecutionServiceServer interface {
	mustEmbedUnimplementedExecutionServiceServer()
}

func RegisterExecutionServiceServer(s grpc.ServiceRegistrar, srv ExecutionServiceServer) {
	// If the following call pancis, it indicates UnimplementedExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutionService_ServiceDesc, srv)
}

func _ExecutionService_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_ApproveCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).ApproveCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_ApproveCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).ApproveCheckpoint(ctx, req.(*ApproveCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_RejectCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutionServiceServer).RejectCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutionService_RejectCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutionServiceServer).RejectCheckpoint(ctx, req.(*RejectCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutionService_StreamRunEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRunEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExecutionServiceServer).StreamRunEvents(m, &grpc.GenericServerStream[StreamRunEventsRequest, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutionService_StreamRunEventsServer = grpc.ServerStreamingServer[RunEvent]

// ExecutionService_ServiceDesc is the grpc.ServiceDesc for ExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "execution.v1.ExecutionService",
	HandlerType: (*ExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _ExecutionService_StartRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _ExecutionService_GetRun_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _ExecutionService_ListRuns_Handler,
		},
		{
			MethodName: "ApproveCheckpoint",
			Handler:    _ExecutionService_ApproveCheckpoint_Handler,
		},
		{
			MethodName: "RejectCheckpoint",
			Handler:    _ExecutionService_RejectCheckpoint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRunEvents",
			Handler:       _ExecutionService_StreamRunEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "execution/v1/execution.proto",
}
