package flowir

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"
)

// Codegen renders an IR to deterministic acpx TypeScript source.
//
// Output structure:
//
//	import { defineFlow, node, edge } from "acpx";
//	export default defineFlow({
//	  id: "...", name: "...",
//	  start: "...",
//	  nodes: [ ... ],
//	  edges: [ ... ],
//	});
//
// Each node kind maps to an acpx helper (acpNode, actionNode, computeNode,
// decisionNode, checkpointNode, forkNode, joinNode, endNode). The output is
// stable: arrays are emitted in IR order with no maps, so the same IR always
// produces byte-identical .flow.ts.
func Codegen(ir *IR) (string, error) {
	if ir == nil {
		return "", fmt.Errorf("nil IR")
	}
	var buf bytes.Buffer
	t := template.Must(template.New("flow").Funcs(template.FuncMap{
		"jsonString": jsonString,
		"args":       renderArgs,
		"renderNode": renderNode,
	}).Parse(flowTpl))
	if err := t.Execute(&buf, ir); err != nil {
		return "", err
	}
	return buf.String(), nil
}

const flowTpl = `// Generated by flowir.Codegen — do not edit.
import {
  defineFlow,
  acpNode,
  actionNode,
  computeNode,
  decisionNode,
  checkpointNode,
  forkNode,
  joinNode,
  endNode,
  edge,
} from "acpx";

export default defineFlow({
  id: {{ jsonString .ID }},
  name: {{ jsonString .Name }},
  start: {{ jsonString .Start }},
  nodes: [
{{- range .Nodes }}
    {{ renderNode . }},
{{- end }}
  ],
  edges: [
{{- range .Edges }}
    edge({{ jsonString .From }}, {{ jsonString .To }}{{ if .Condition }}, { condition: {{ jsonString .Condition }} }{{ end }}),
{{- end }}
  ],
});
`

func jsonString(s string) string {
	b, _ := jsonMarshalString(s)
	return b
}

func jsonMarshalString(s string) (string, error) {
	// Minimal JSON-string escaper sufficient for IDs/names/conditions.
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\', '"':
			b.WriteByte('\\')
			b.WriteRune(r)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String(), nil
}

func renderArgs(args map[string]any) string {
	if len(args) == 0 {
		return "{}"
	}
	keys := make([]string, 0, len(args))
	for k := range args {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		parts = append(parts, fmt.Sprintf("%s: %s", jsonString(k), litValue(args[k])))
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func litValue(v any) string {
	switch t := v.(type) {
	case string:
		return jsonString(t)
	case bool:
		if t {
			return "true"
		}
		return "false"
	case float64:
		return fmt.Sprintf("%g", t)
	case int:
		return fmt.Sprintf("%d", t)
	case nil:
		return "null"
	default:
		return jsonString(fmt.Sprintf("%v", v))
	}
}

func renderNode(n Node) string {
	switch n.Kind {
	case NodeACP:
		return fmt.Sprintf(`acpNode({ id: %s, title: %s, agentId: %s, skill: %s, prompt: %s, args: %s })`,
			jsonString(n.ID), jsonString(n.Title), jsonString(n.AgentID), jsonString(n.Skill), jsonString(n.Prompt), renderArgs(n.Args))
	case NodeAction:
		return fmt.Sprintf(`actionNode({ id: %s, title: %s, fn: %s, args: %s })`,
			jsonString(n.ID), jsonString(n.Title), jsonString(n.Fn), renderArgs(n.Args))
	case NodeCompute:
		return fmt.Sprintf(`computeNode({ id: %s, title: %s, fn: %s, args: %s })`,
			jsonString(n.ID), jsonString(n.Title), jsonString(n.Fn), renderArgs(n.Args))
	case NodeDecision:
		var parts []string
		for _, b := range n.Branches {
			parts = append(parts, fmt.Sprintf("{ when: %s, to: %s }", jsonString(b.When), jsonString(b.To)))
		}
		return fmt.Sprintf(`decisionNode({ id: %s, title: %s, branches: [ %s ] })`,
			jsonString(n.ID), jsonString(n.Title), strings.Join(parts, ", "))
	case NodeCheckpoint:
		approvers := "[]"
		if len(n.Approvers) > 0 {
			qs := make([]string, 0, len(n.Approvers))
			for _, a := range n.Approvers {
				qs = append(qs, jsonString(a))
			}
			approvers = "[ " + strings.Join(qs, ", ") + " ]"
		}
		return fmt.Sprintf(`checkpointNode({ id: %s, title: %s, prompt: %s, approvers: %s, timeoutSeconds: %d, onTimeout: %s })`,
			jsonString(n.ID), jsonString(n.Title), jsonString(n.Prompt), approvers, n.TimeoutSeconds, jsonString(n.OnTimeout))
	case NodeFork:
		return fmt.Sprintf(`forkNode({ id: %s, title: %s })`, jsonString(n.ID), jsonString(n.Title))
	case NodeJoin:
		return fmt.Sprintf(`joinNode({ id: %s, title: %s })`, jsonString(n.ID), jsonString(n.Title))
	case NodeEnd:
		return fmt.Sprintf(`endNode({ id: %s, title: %s })`, jsonString(n.ID), jsonString(n.Title))
	default:
		return fmt.Sprintf(`actionNode({ id: %s, title: %s, fn: %s, args: %s })`,
			jsonString(n.ID), jsonString(n.Title), jsonString(n.Fn), renderArgs(n.Args))
	}
}
